---
# Deployable for Deployment
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: gstore-deployable-deployment-sales
  namespace: gstore-namespace-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    mcmapp: gstore-namespace
    submcmapp: sales
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: gstore-sales
      namespace: gstore-namespace-app-ns
    spec:
      selector:
        matchLabels:
          app: gstore-application
          subname: sales
      replicas: 1
      template:
        metadata:
          labels:
            app: gstore-application
            subname: sales
        spec:
          containers:
            - name: my-container
              image: "gandhicloudlab/cpro-bankweb:latest"
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: 9030
                  protocol: TCP
                - name: https
                  containerPort: 8082
---
# Deployable for Service
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: gstore-deployable-service-sales
  namespace: gstore-namespace-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false" 
  labels:
    mcmapp: gstore-namespace
    submcmapp: sales
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: gstore-sales
      namespace: gstore-namespace-app-ns
      labels:
        app: gstore-application
        subname: sales      
    spec:
      type: ClusterIP
      ports:
        - name: my-http
          port: 9030
          targetPort: 9030
      selector:
        app: gstore-application
        subname: sales
---
# Deployable for Route
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: gstore-deployable-route-sales
  namespace: gstore-namespace-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    mcmapp: gstore-namespace
    submcmapp: sales
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: gstore-sales
      namespace: gstore-namespace-app-ns
      labels:
        app: gstore-application
        subname: sales      
    spec:
      path: /
      to:
        kind: Service
        name: gstore-sales
        weight: 100
      port:
        targetPort: my-http
---  