---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: gstore-namespace-application
  namespace: gstore-namespace-subscription-ns
  labels:
    mcmapp: gstore-namespace
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      mcmapp: gstore-namespace
    