---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: gstore-namespace
  namespace: gstore-namespace-subscription-ns
  labels:
    app: gstore-namespace-application
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - gstore-namespace-application
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
