---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: gstore-namespace-placementrule
  namespace: gstore-namespace-subscription-ns
  labels:
    mcmapp: gstore-namespace
spec:
  clusterReplicas: 1
  clusterLabels:
    matchExpressions:
      - key: name
        operator: In
        values:
        - ocp43-mcm-gan-a