---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: gstore-namespace-subscription
  namespace: gstore-namespace-subscription-ns
  labels:
    mcmapp: gstore-namespace
spec:
  channel: gstore-namespace-channel-ns/gstore-namespace-channel
  packageFilter:
    labelSelector:
      matchLabels:
        mcmapp: gstore-namespace
        submcmapp: sales
  placement:
    placementRef:
      name: gstore-namespace-placementrule
      kind: PlacementRule
      group: app.ibm.com
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: gstore-namespace-app-ns