---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: subscription-gstore-namespace-web
  namespace: gstore-namespace-subscription-ns
  labels:
    app: gstore-namespace-application
spec:
  channel: gstore-namespace-channel-ns/gstore-namespace-channel
  packageFilter:
    version: ">=1.x"
    labelSelector:
      matchLabels:
        app: gstore-namespace-application
        subApp: web
  placement:
    placementRef:
      name: gstore-namespace-web
      kind: PlacementRule
      group: app.ibm.com
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: gstore-namespace-app-ns      
  